### ISSUE TITLE
Could you please provide an example of imageData.txt?

### ISSUE THREAD

**Issue by zjnyly** [ksakash/cuda_stitch#1]
I'm really happy to find your repository which is very useful to me. But I'm a little bit confused about the files mentioned in code.
```
std::string filename = "/home/ksakash/misc/Drone-Image-Stitching/datasets/imageData.txt";
    std::vector<imageData> dataMatrix;
    readData (filename, dataMatrix);
    std::vector<cv::Mat> imageList;
    std::string base_path = "/home/ksakash/misc/Drone-Image-Stitching/datasets/images/";
    getImageList (imageList, dataMatrix, base_path);
    changePerspective (imageList, dataMatrix);
    imageList.clear();
    base_path = "/home/ksakash/misc/Drone-Image-Stitching/temp/";
    getImageList (imageList, dataMatrix, base_path);
    cv::Mat result = combine (imageList);
    cv::imwrite ("/home/ksakash/misc/Drone-Image-Stitching/results/result.png", result);
```

Especially imageData.txt, if you can provide this file, it will help me a lot! Thanks!

**Comment by ksakash** [comment]
Hey @zjnyly, the `imageData.txt` basically contains the GPS location where a particular image was taken. 

The format of data in the  file is like this: `<image_filename>, <x/longtitude>, <y/latitude>, <z/altitude>, <yaw>, <pitch>, <roll>`
The file contains one entry corresponding to one image.

Ex:

```
17.jpg,4.495,-0.355,11.720,84.543,7.513,-3.157
18.jpg,0.030,2.393,12.118,89.234,3.526,-4.630
19.jpg,4.236,3.479,12.284,90.602,5.227,-1.955
20.jpg,-0.299,6.958,11.757,89.609,1.856,-5.088
21.jpg,6.479,5.706,12.043,89.361,0.676,-3.620
22.jpg,0.399,9.905,12.005,92.710,1.561,-0.738
23.jpg,9.280,5.108,11.884,89.635,4.849,2.029
24.jpg,4.326,9.540,11.865,93.869,4.808,-4.277
25.jpg,9.908,4.122,11.901,88.254,1.465,-3.520
26.jpg,5.153,12.609,11.756,89.142,0.151,-3.700
```

**Comment by zjnyly** [comment]
> Hey @zjnyly, the `imageData.txt` basically contains the GPS location where a particular image was taken.
> 
> The format of data in the file is like this: `<image_filename>, <x/longtitude>, <y/latitude>, <z/altitude>, <yaw>, <pitch>, <roll>` The file contains one entry corresponding to one image.
> 
> Ex:
> 
> ```
> 17.jpg,4.495,-0.355,11.720,84.543,7.513,-3.157
> 18.jpg,0.030,2.393,12.118,89.234,3.526,-4.630
> 19.jpg,4.236,3.479,12.284,90.602,5.227,-1.955
> 20.jpg,-0.299,6.958,11.757,89.609,1.856,-5.088
> 21.jpg,6.479,5.706,12.043,89.361,0.676,-3.620
> 22.jpg,0.399,9.905,12.005,92.710,1.561,-0.738
> 23.jpg,9.280,5.108,11.884,89.635,4.849,2.029
> 24.jpg,4.326,9.540,11.865,93.869,4.808,-4.277
> 25.jpg,9.908,4.122,11.901,88.254,1.465,-3.520
> 26.jpg,5.153,12.609,11.756,89.142,0.151,-3.700
> ```

Thank you for your kindness! Your code really helped me a lot!
